import 'controller/register_adolescent_activity_family_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/presentation/register_adolescent_activity_family_page/register_adolescent_activity_family_page.dart';import 'package:shashankgowdasp_s_application1/presentation/register_adolescent_activity_one_page/register_adolescent_activity_one_page.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_image_3.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_subtitle_3.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/custom_app_bar.dart';class RegisterAdolescentActivityFamilyTabContainerScreen extends GetWidget<RegisterAdolescentActivityFamilyTabContainerController> {const RegisterAdolescentActivityFamilyTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 112.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 18.h, right: 154.h), child: Row(children: [AppbarImage3(svgPath: ImageConstant.imgArrowleftBlack900, margin: EdgeInsets.only(bottom: 1.v), onTap: () {onTapArrowleftone();}), AppbarSubtitle3(text: "msg_register_adolescent".tr, margin: EdgeInsets.only(left: 12.h, top: 2.v))])), SizedBox(height: 35.v), Container(height: 35.v, width: double.maxFinite, child: TabBar(controller: controller.tabviewController, isScrollable: true, labelColor: appTheme.black900.withOpacity(0.9), labelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Source Sans Pro', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.black900.withOpacity(0.9), unselectedLabelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Source Sans Pro', fontWeight: FontWeight.w700), indicatorColor: appTheme.lightBlue400, tabs: [Tab(child: Padding(padding: EdgeInsets.only(bottom: 14.v), child: Text("msg_adolescent_details".tr))), Tab(child: Padding(padding: EdgeInsets.only(top: 1.v, bottom: 12.v), child: Text("lbl_family_details".tr))), Tab(child: Padding(padding: EdgeInsets.only(top: 1.v, bottom: 12.v), child: Text("msg_health_and_lifestyle".tr)))]))]), styleType: Style.bgShadow_1), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: SizedBox(height: 528.v, child: TabBarView(controller: controller.tabviewController, children: [RegisterAdolescentActivityFamilyPage(), RegisterAdolescentActivityOnePage(), RegisterAdolescentActivityOnePage()])))))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
