import 'controller/splashactivity_one_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_elevated_button.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_outlined_button.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_text_form_field.dart';class SplashactivityOneScreen extends GetWidget<SplashactivityOneController> {const SplashactivityOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: theme.colorScheme.primary, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 39.h, vertical: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 26.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_welcome_to".tr, style: CustomTextStyles.headlineSmallBlack900), TextSpan(text: "lbl_saheli_app".tr, style: CustomTextStyles.headlineSmallLightblue400_1)]), textAlign: TextAlign.left), Container(width: 212.h, margin: EdgeInsets.only(top: 2.v, right: 67.h), child: Text("msg_please_proceed_with".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeBlack900_1)), SizedBox(height: 15.v), Text("lbl_mobile".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 3.v), CustomTextFormField(controller: controller.phonenumberoneController, hintText: "lbl_91".tr, hintStyle: theme.textTheme.bodyLarge!, contentPadding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 13.v)), SizedBox(height: 24.v), Text("lbl_password".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 3.v), CustomTextFormField(controller: controller.passwordController), SizedBox(height: 24.v), Text("lbl_role".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 3.v), CustomTextFormField(controller: controller.selectroleoneController, hintText: "lbl_select_role".tr, hintStyle: theme.textTheme.bodyLarge!, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdropdownOnsecondarycontainer)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(left: 18.h, top: 13.v, bottom: 13.v)), SizedBox(height: 29.v), CustomElevatedButton(height: 56.v, text: "lbl_sign_up".tr, buttonStyle: CustomButtonStyles.outlineBlack, buttonTextStyle: theme.textTheme.headlineSmall!, onTap: () {onTapSignup();}), GestureDetector(onTap: () {onTapTxtIfyoualreadyhave();}, child: Container(width: 231.h, margin: EdgeInsets.only(top: 25.v, right: 48.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_if_you_already_have2".tr, style: CustomTextStyles.bodyLarge18), TextSpan(text: "lbl_login_here".tr, style: CustomTextStyles.titleMediumBlue700.copyWith(decoration: TextDecoration.underline))]), textAlign: TextAlign.left)))])), bottomNavigationBar: CustomOutlinedButton(height: 56.v, text: "lbl_login".tr, margin: EdgeInsets.only(left: 39.h, right: 43.h, bottom: 29.v), buttonStyle: CustomButtonStyles.outlineLightBlueTL4, buttonTextStyle: CustomTextStyles.headlineSmallLightblue400, onTap: () {onTapLogin();}))); } 
/// Navigates to the splashactivityTwoScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the splashactivityTwoScreen.
onTapLogin() { Get.toNamed(AppRoutes.splashactivityTwoScreen, ); } 
/// Navigates to the otpactivityScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the otpactivityScreen.
onTapSignup() { Get.toNamed(AppRoutes.otpactivityScreen, ); } 
/// Navigates to the splashactivityTwoScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the splashactivityTwoScreen.
onTapTxtIfyoualreadyhave() { Get.toNamed(AppRoutes.splashactivityTwoScreen, ); } 
 }
