import 'controller/register_adolescent_activity_six_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/presentation/register_adolescent_activity_health_page/register_adolescent_activity_health_page.dart';import 'package:shashankgowdasp_s_application1/presentation/register_adolescent_activity_six_page/register_adolescent_activity_six_page.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_image_3.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/custom_app_bar.dart';class RegisterAdolescentActivitySixTabContainerScreen extends GetWidget<RegisterAdolescentActivitySixTabContainerController> {const RegisterAdolescentActivitySixTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: CustomAppBar(height: 112.v, centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(left: 18.h, right: 149.h), child: Row(children: [AppbarImage3(svgPath: ImageConstant.imgArrowleftPrimary, onTap: () {onTapArrowleftone();}), AppbarSubtitle(text: "msg_register_adolescent".tr, margin: EdgeInsets.only(left: 12.h, top: 1.v))])), SizedBox(height: 35.v), Container(height: 35.v, width: double.maxFinite, child: TabBar(controller: controller.tabviewController, isScrollable: true, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Source Sans Pro', fontWeight: FontWeight.w700), unselectedLabelColor: theme.colorScheme.primary, unselectedLabelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Source Sans Pro', fontWeight: FontWeight.w700), indicatorColor: theme.colorScheme.primary, tabs: [Tab(child: Padding(padding: EdgeInsets.only(top: 1.v, bottom: 12.v), child: Text("lbl_family_details".tr))), Tab(child: Padding(padding: EdgeInsets.only(top: 1.v, bottom: 12.v), child: Text("msg_health_and_lifestyle".tr))), Tab(child: Padding(padding: EdgeInsets.only(bottom: 14.v), child: Text("msg_additional_information".tr)))]))]), styleType: Style.bgShadow_3), body: SizedBox(height: 528.v, child: TabBarView(controller: controller.tabviewController, children: [RegisterAdolescentActivitySixPage(), RegisterAdolescentActivityHealthPage(), RegisterAdolescentActivityHealthPage()])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
