import 'controller/selectfacilityactivity_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_elevated_button.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_text_form_field.dart';class SelectfacilityactivityScreen extends GetWidget<SelectfacilityactivityController> {const SelectfacilityactivityScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, backgroundColor: theme.colorScheme.primary, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 40.h, vertical: 29.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_select_facility".tr, style: CustomTextStyles.headlineSmallBlack900_1), SizedBox(height: 17.v), Text("lbl_district".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 2.v), CustomTextFormField(controller: controller.selectdistrictController, hintText: "lbl_select_district".tr, hintStyle: theme.textTheme.bodyLarge!, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdropdownOnsecondarycontainer)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(left: 18.h, top: 13.v, bottom: 13.v)), SizedBox(height: 24.v), Text("lbl_block".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 3.v), CustomTextFormField(controller: controller.selectblockoneController, hintText: "lbl_select_block".tr, hintStyle: theme.textTheme.bodyLarge!, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdropdownOnsecondarycontainer)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(left: 18.h, top: 13.v, bottom: 13.v)), SizedBox(height: 26.v), Text("lbl_panchayath".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 1.v), CustomTextFormField(controller: controller.selectpanchayatController, hintText: "msg_select_panchayath".tr, hintStyle: theme.textTheme.bodyLarge!, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdropdownOnsecondarycontainer)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(left: 18.h, top: 13.v, bottom: 13.v)), SizedBox(height: 26.v), Text("lbl_village2".tr, style: theme.textTheme.bodyLarge), SizedBox(height: 1.v), CustomTextFormField(controller: controller.selectvillageController, hintText: "lbl_select_village".tr, hintStyle: theme.textTheme.bodyLarge!, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(svgPath: ImageConstant.imgArrowdropdownOnsecondarycontainer)), suffixConstraints: BoxConstraints(maxHeight: 48.v), contentPadding: EdgeInsets.only(left: 18.h, top: 13.v, bottom: 13.v)), SizedBox(height: 45.v), CustomElevatedButton(height: 56.v, text: "lbl_finish_setup".tr, buttonStyle: CustomButtonStyles.outlineBlackTL4, buttonTextStyle: theme.textTheme.headlineSmall!, onTap: () {onTapFinishsetup();}), SizedBox(height: 5.v)])))); } 
/// Navigates to the mainactivityOneScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the mainactivityOneScreen.
onTapFinishsetup() { Get.toNamed(AppRoutes.mainactivityOneScreen, ); } 
 }
