import 'controller/register_adolescent_one_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_image.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_elevated_button.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_text_form_field.dart';class RegisterAdolescentOneScreen extends GetWidget<RegisterAdolescentOneController> {const RegisterAdolescentOneScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: CustomAppBar(leadingWidth: 42.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftPrimary, margin: EdgeInsets.only(left: 18.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowleftone();}), title: AppbarSubtitle(text: "msg_register_adolescent".tr, margin: EdgeInsets.only(left: 12.h)), styleType: Style.bgShadow_3), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(child: CustomTextFormField(width: double.maxFinite, controller: controller.basicdetailsController, margin: EdgeInsets.only(bottom: 5.v), hintText: "lbl_basic_details".tr, hintStyle: CustomTextStyles.titleMediumBlack900_1, textInputAction: TextInputAction.done, prefix: Container(padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 5.v), margin: EdgeInsets.fromLTRB(30.h, 30.v, -25.h, 30.v), decoration: BoxDecoration(color: appTheme.greenA70001, borderRadius: BorderRadius.circular(8.h)), child: CustomImageView(svgPath: ImageConstant.imgCheckmarkPrimary)), prefixConstraints: BoxConstraints(maxHeight: 688.v), contentPadding: EdgeInsets.only(top: 332.v, right: 30.h, bottom: 332.v), borderDecoration: TextFormFieldStyleHelper.fillBlueGray1, fillColor: appTheme.blueGray5001))), bottomNavigationBar: Container(margin: EdgeInsets.only(left: 5.h, right: 4.h, bottom: 4.v), decoration: AppDecoration.surface, child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomElevatedButton(width: 112.h, text: "lbl_cancel".tr, buttonStyle: CustomButtonStyles.fillGrayTL4, buttonTextStyle: CustomTextStyles.titleMediumGray500), CustomElevatedButton(width: 235.h, text: "lbl_save".tr, margin: EdgeInsets.only(left: 4.h), buttonStyle: CustomButtonStyles.fillLightBlue, buttonTextStyle: theme.textTheme.titleMedium!)])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
