import 'controller/endtrainingactivity_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_image.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_title.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/custom_app_bar.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_elevated_button.dart';import 'package:shashankgowdasp_s_application1/widgets/custom_text_form_field.dart';class EndtrainingactivityScreen extends GetWidget<EndtrainingactivityController> {const EndtrainingactivityScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: CustomAppBar(leadingWidth: 41.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftOnsecondarycontainer, margin: EdgeInsets.only(left: 17.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowleftone();}), title: AppbarTitle(text: "lbl_end_training".tr, margin: EdgeInsets.only(left: 15.h)), styleType: Style.bgShadow), body: Container(width: 335.h, margin: EdgeInsets.fromLTRB(12.h, 13.v, 12.h, 5.v), padding: EdgeInsets.symmetric(vertical: 15.v), decoration: AppDecoration.outlineSecondaryContainer1.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_leadership_development".tr, style: CustomTextStyles.titleMediumBlack900)), Padding(padding: EdgeInsets.only(left: 16.h, top: 9.v), child: Text("msg_adols_enrolled".tr, style: CustomTextStyles.bodyLargeBlack900_1)), Padding(padding: EdgeInsets.only(left: 17.h, top: 11.v), child: Text("msg_present".tr, style: CustomTextStyles.bodyLargeBlack900_1)), Padding(padding: EdgeInsets.only(left: 17.h, top: 7.v), child: Text("msg_absent".tr, style: CustomTextStyles.bodyLargeBlack900_1)), SizedBox(height: 27.v), Divider(), Padding(padding: EdgeInsets.only(left: 19.h, top: 17.v), child: Text("lbl_end_date".tr, style: CustomTextStyles.bodyMediumBlack900)), Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(left: 18.h, top: 4.v, right: 18.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 9.v), decoration: AppDecoration.fillGray200.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(left: 8.h, top: 4.v), child: Text("msg_15_july_2023_01_20".tr, style: CustomTextStyles.bodyLargeBlack900_3)), CustomImageView(svgPath: ImageConstant.imgCalendar, height: 24.v, width: 22.h, margin: EdgeInsets.only(top: 1.v))]))), Padding(padding: EdgeInsets.only(left: 19.h, top: 36.v), child: Text("lbl_summary".tr, style: CustomTextStyles.bodyMediumBlack900)), CustomTextFormField(controller: controller.edittextController, margin: EdgeInsets.only(left: 19.h, top: 3.v, right: 18.h), textInputAction: TextInputAction.done, alignment: Alignment.center, borderDecoration: TextFormFieldStyleHelper.fillGray), CustomElevatedButton(text: "lbl_end_training".tr, margin: EdgeInsets.fromLTRB(17.h, 17.v, 18.h, 4.v), buttonStyle: CustomButtonStyles.fillLightBlue, buttonTextStyle: CustomTextStyles.titleLargePrimary, onTap: () {onTapEndtraining();}, alignment: Alignment.center)])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
/// Navigates to the trainingactivityScreen when the action is triggered.

/// When the action is triggered, this function uses the [Get] package to
/// push the named route for the trainingactivityScreen.
onTapEndtraining() { Get.toNamed(AppRoutes.trainingactivityScreen, ); } 
 }
