import 'controller/register_adolescent_activity_four_tab_container_controller.dart';import 'package:flutter/material.dart';import 'package:shashankgowdasp_s_application1/core/app_export.dart';import 'package:shashankgowdasp_s_application1/presentation/register_adolescent_activity_four_page/register_adolescent_activity_four_page.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_image.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/appbar_subtitle.dart';import 'package:shashankgowdasp_s_application1/widgets/app_bar/custom_app_bar.dart';class RegisterAdolescentActivityFourTabContainerScreen extends GetWidget<RegisterAdolescentActivityFourTabContainerController> {const RegisterAdolescentActivityFourTabContainerScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: 216.h, child: Column(children: [Container(decoration: AppDecoration.primary, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 16.v), CustomAppBar(height: 24.v, leadingWidth: 42.h, leading: AppbarImage(svgPath: ImageConstant.imgArrowleftPrimary, margin: EdgeInsets.only(left: 18.h), onTap: () {onTapArrowleftone();}), title: AppbarSubtitle(text: "msg_register_adolescent".tr, margin: EdgeInsets.only(left: 12.h))), SizedBox(height: 36.v), Container(height: 35.v, width: 347.h, child: TabBar(controller: controller.tabviewController, isScrollable: true, labelColor: theme.colorScheme.primary, labelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Source Sans Pro', fontWeight: FontWeight.w700), unselectedLabelColor: theme.colorScheme.primary, unselectedLabelStyle: TextStyle(fontSize: 16.fSize, fontFamily: 'Source Sans Pro', fontWeight: FontWeight.w700), indicatorColor: theme.colorScheme.primary, tabs: [Tab(child: Text("msg_health_and_lifestyle".tr)), Tab(child: Text("msg_additional_information".tr))]))])), SizedBox(height: 528.v, child: TabBarView(controller: controller.tabviewController, children: [RegisterAdolescentActivityFourPage(), RegisterAdolescentActivityFourPage()]))])))); } 


/// Navigates to the previous screen.
///
/// When the action is triggered, this function uses the [Get] package to 
/// navigate to the previous screen in the navigation stack.
onTapArrowleftone() { Get.back(); } 
 }
